; Form Designer for Purebasic - 5.21
; Warning: this file uses a strict syntax, if you edit it, make sure to respect the Form Designer limitation or it won't be opened again.

;
; This code is automatically generated by the FormDesigner.
; Manual modification is possible to adjust existing commands, but anything else will be dropped when the code is compiled.
; Event procedures needs to be put in another source file.
;


Procedure OpenReqWindow_01(x = 0, y = 0, width = 485, height = 176)
    OpenWindow(#ReqWindow_01, x, y, width, height, "", #PB_Window_ScreenCentered | #PB_Window_BorderLess|#PB_Window_Tool|#PB_Window_Invisible)
    
    
    CanvasGadget(#_SKINBASE_T00,0, 0, 485, 176)    
    StartDrawing(CanvasOutput(#_SKINBASE_T00))
    DrawAlphaImage(ImageID(#_SKINIMAGE_T00), 0, 0)
    StopDrawing()
    DisableGadget( #_SKINBASE_T00, #True) 
  
    TextGadget(#ReqText0, 90, 31, 339, 14, Dialog_Message_Top$,#PB_Text_Center)
    SetGadgetColor(#ReqText0, #PB_Gadget_FrontColor,RGB(192, 192, 192)) 
    SetGadgetColor(#ReqText0, #PB_Gadget_BackColor,$FF000000)
            
    TextGadget(#ReqText1, 86, 50, 360, 82, Dialog_Message_Mid$)
    SetGadgetColor(#ReqText1, #PB_Gadget_BackColor,RGB(227, 227, 228));RGBA(208, 136, 208, 0)
   
    ;
    SetGadgetFont(#ReqText0, FontID(FontID_FIXPLAIN7_12))
    SetGadgetFont(#ReqText1, FontID(FontID_DROIDSANS_09))
    
    ButtonImageGadget(#Icon_0, 18, 25, 40, 40, 0)
    ButtonImageGadget(#Icon_1, 18, 78, 40, 40, 0)

EndProcedure



; IDE Options = PureBasic 5.21 LTS (Windows - x64)
; CursorPosition = 29
; Folding = -
; EnableAsm
; EnableUnicode
; EnableXP
; UseMainFile = ..\7z_Main_Source.pb
; CurrentDirectory = ..\..\..\Test-Env\